#!/bin/bash

echo "========================================="
echo "  SEKRETERYA APP - SERVİS YÖNETİMİ"
echo "========================================="
echo ""
echo "📋 DURUM KONTROLÜ:"
echo "  sudo systemctl status sekreteryaapp"
echo "  sudo systemctl status prisma-studio"
echo ""
echo "🔄 YÖNETİM KOMUTLARI:"
echo "  sudo systemctl start sekreteryaapp    # Başlat"
echo "  sudo systemctl stop sekreteryaapp     # Durdur"
echo "  sudo systemctl restart sekreteryaapp  # Yeniden başlat"
echo "  sudo systemctl enable sekreteryaapp   # Otomatik başlatmayı aç"
echo "  sudo systemctl disable sekreteryaapp  # Otomatik başlatmayı kapat"
echo ""
echo "📊 LOGLAR:"
echo "  sudo journalctl -u sekreteryaapp -f   # Canlı loglar"
echo "  sudo journalctl -u sekreteryaapp -n 50 # Son 50 log"
echo "  sudo journalctl -u prisma-studio -f   # Prisma Studio logları"
echo ""
echo "🌐 ERİŞİM:"
echo "  🔒 HTTPS (ÖNERİLEN): https://sekreterya.local"
echo "  🔒 IP Adresi: https://192.168.1.133"
echo "  🔒 Prisma Studio: https://sekreterya.local:5556"
echo "  ⚡ HTTP: Otomatik HTTPS'e yönlenir"
echo ""
echo "🔧 GELİŞTİRME MODU:"
echo "  cd /home/ihb/Desktop/projeler/sekreteryaapp"
echo "  sudo systemctl stop sekreteryaapp  # Production'ı durdur"
echo "  npm run dev                         # Dev modda başlat"
echo ""
echo "🚀 PRODUCTION MODU:"
echo "  npm run build                       # Build yap"
echo "  sudo systemctl restart sekreteryaapp # Service'i yeniden başlat"
echo ""
echo "========================================="

